import type { RosterDetachment } from '../stores/rosterStore.ts';

export function generateRosterText(
  name: string,
  pointsLimit: number,
  detachments: RosterDetachment[],
  totalPoints: number,
): string {
  const lines: string[] = [];

  lines.push('\u2550'.repeat(39));
  lines.push(`  ${name}`);
  lines.push(`  Points: ${totalPoints} / ${pointsLimit}`);
  lines.push(`  Detachments: ${detachments.length}`);
  lines.push('\u2550'.repeat(39));
  lines.push('');

  for (const det of detachments) {
    const detPoints = det.entries.reduce((s, e) => s + e.totalCost, 0);
    lines.push(`\u25B6 ${det.name} [${det.type}] (${detPoints} pts)`);
    lines.push('\u2500'.repeat(39));

    // Group entries by slot
    const slotNames = Object.keys(det.slots);
    for (const slot of slotNames) {
      const status = det.slots[slot];
      const slotEntries = det.entries.filter((e) => e.category === slot);
      if (slotEntries.length === 0 && status.max === 0) continue;

      lines.push(`  ${slot} (${status.filled}/${status.max === 999 ? '\u221E' : status.max})`);
      for (const e of slotEntries) {
        const qty = e.quantity > 1 ? ` x${e.quantity}` : '';
        lines.push(`    ${e.name}${qty}  [${e.totalCost} pts]`);
      }
      if (slotEntries.length === 0) {
        lines.push('    \u2014');
      }
    }
    lines.push('');
  }

  lines.push('\u2500'.repeat(39));
  lines.push(`  Total: ${totalPoints} pts`);
  lines.push('');
  lines.push('Generated by Solar Auxilia List Builder');

  return lines.join('\n');
}

export function downloadRosterText(text: string, filename: string) {
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
