import type { RosterEntry } from '../stores/rosterStore.ts';
import { FOC_CATEGORIES } from '../types/index.ts';

export function generateRosterText(
  name: string,
  detachment: string,
  pointsLimit: number,
  entries: RosterEntry[],
  totalPoints: number,
): string {
  const lines: string[] = [];

  lines.push('═══════════════════════════════════════');
  lines.push(`  ${name}`);
  lines.push(`  Detachment: ${detachment}`);
  lines.push(`  Points: ${totalPoints} / ${pointsLimit}`);
  lines.push('═══════════════════════════════════════');
  lines.push('');

  for (const cat of FOC_CATEGORIES) {
    const catEntries = entries.filter((e) => e.category === cat);
    if (catEntries.length === 0) continue;

    lines.push(`── ${cat} ${'─'.repeat(Math.max(0, 33 - cat.length))}`);
    for (const e of catEntries) {
      const qty = e.quantity > 1 ? ` x${e.quantity}` : '';
      lines.push(`  ${e.name}${qty}  [${e.totalCost} pts]`);
    }
    lines.push('');
  }

  lines.push('───────────────────────────────────────');
  lines.push(`  Total: ${totalPoints} pts`);
  lines.push('');
  lines.push('Generated by Solar Auxilia List Builder');

  return lines.join('\n');
}

export function downloadRosterText(text: string, filename: string) {
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
